spring:
  h2:
    console:
      enabled: true
#  jpa:
#    defer-datasource-initialization: true
  datasource:
  #  initialization-mode: never
    url: jdbc:h2:mem:7cf6e91d-d5af-40f5-abbe-06a8f9e2f5ae
    driver-class-name: org.h2.Driver
  sql:
    init:
      enabled: true
spring.jpa.defer-datasource-initialization: true
#  datasource:
#    url:jdbc:h2:mem:7cf6e91d-d5af-40f5-abbe-06a8f9e2f5ae
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8089