spring:
  h2:
    console:
      enabled: true
#  jpa:
#    defer-datasource-initialization: true
  datasource:
  #  initialization-mode: never
    url: jdbc url
    driver-class-name: org.h2.Driver
  sql:
    init:
      enabled: true
spring.jpa.defer-datasource-initialization: true
#  datasource:
#    url:jdbc url
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8089