server:
  port: 8089

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql:
          true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_community
    username: root
    password: jisoo
  h2:
    console:
      enabled: true
  sql:
    init:
      enabled: true